#!/usr/bin/env bash

set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
RUNTIME_DIR="$ROOT/.repository_steward/dev_services"
STATE_FILE="$RUNTIME_DIR/pids.env"
BACKEND_DIR="$ROOT/backend"
FRONTEND_DIR="$ROOT/frontend"

HOST_ADDRESS="127.0.0.1"
BACKEND_PORT=8002
FRONTEND_PORT=7788
ACTION="start"

usage() {
    cat <<'EOF'
Usage: ./start_services.sh [start|stop|restart|status] [options]

Options:
  --host-address HOST    Bind address (default: 127.0.0.1)
  --backend-port PORT    Backend port (default: 8002)
  --frontend-port PORT   Frontend port (default: 7788)
  -h, --help             Show this help

The aliases --stop, --restart, and --status are also supported.
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        start|stop|restart|status)
            ACTION="$1"
            shift
            ;;
        --stop|--restart|--status)
            ACTION="${1#--}"
            shift
            ;;
        --host-address)
            [[ $# -ge 2 ]] || { echo "$1 requires a value." >&2; exit 1; }
            HOST_ADDRESS="$2"
            shift 2
            ;;
        --backend-port)
            [[ $# -ge 2 ]] || { echo "$1 requires a value." >&2; exit 1; }
            BACKEND_PORT="$2"
            shift 2
            ;;
        --frontend-port)
            [[ $# -ge 2 ]] || { echo "$1 requires a value." >&2; exit 1; }
            FRONTEND_PORT="$2"
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "Unknown argument: $1" >&2
            usage >&2
            exit 1
            ;;
    esac
done

is_running() {
    local pid="${1:-}"
    [[ "$pid" =~ ^[0-9]+$ ]] && kill -0 "$pid" 2>/dev/null
}

load_state() {
    BACKEND_PID=""
    FRONTEND_PID=""
    SAVED_HOST_ADDRESS="$HOST_ADDRESS"
    SAVED_BACKEND_PORT="$BACKEND_PORT"
    SAVED_FRONTEND_PORT="$FRONTEND_PORT"

    if [[ -f "$STATE_FILE" ]]; then
        # This file is generated by this script and contains numeric values only.
        # shellcheck disable=SC1090
        source "$STATE_FILE"
    fi
}

child_pids() {
    pgrep -P "$1" 2>/dev/null || true
}

stop_process_tree() {
    local pid="$1"
    local child

    is_running "$pid" || return 0
    for child in $(child_pids "$pid"); do
        stop_process_tree "$child"
    done
    kill "$pid" 2>/dev/null || true
}

wait_for_exit() {
    local pid="$1"
    local attempts=0
    while is_running "$pid" && [[ $attempts -lt 20 ]]; do
        sleep 0.1
        attempts=$((attempts + 1))
    done
    if is_running "$pid"; then
        kill -9 "$pid" 2>/dev/null || true
    fi
}

port_pid() {
    lsof -nP -iTCP:"$1" -sTCP:LISTEN -t 2>/dev/null | head -n 1 || true
}

wait_for_port() {
    local name="$1"
    local pid="$2"
    local port="$3"
    local stdout_path="$4"
    local stderr_path="$5"
    local attempts=0

    while [[ $attempts -lt 120 ]]; do
        if ! is_running "$pid"; then
            echo "$name exited during startup." >&2
            [[ -f "$stdout_path" ]] && tail -n 50 "$stdout_path" >&2
            [[ -f "$stderr_path" ]] && tail -n 50 "$stderr_path" >&2
            return 1
        fi
        if [[ -n "$(port_pid "$port")" ]]; then
            return 0
        fi
        sleep 0.25
        attempts=$((attempts + 1))
    done

    echo "$name did not listen on port $port within 30 seconds." >&2
    [[ -f "$stdout_path" ]] && tail -n 50 "$stdout_path" >&2
    [[ -f "$stderr_path" ]] && tail -n 50 "$stderr_path" >&2
    return 1
}

show_status() {
    load_state
    if [[ ! -f "$STATE_FILE" ]]; then
        echo "No saved service state."
        return 0
    fi

    if is_running "$BACKEND_PID"; then
        echo "backend: running pid=$BACKEND_PID"
    else
        echo "backend: stopped pid=${BACKEND_PID:-unknown}"
    fi
    echo "  stdout: $RUNTIME_DIR/backend.stdout.log"
    echo "  stderr: $RUNTIME_DIR/backend.stderr.log"

    if is_running "$FRONTEND_PID"; then
        echo "frontend: running pid=$FRONTEND_PID"
    else
        echo "frontend: stopped pid=${FRONTEND_PID:-unknown}"
    fi
    echo "  stdout: $RUNTIME_DIR/frontend.stdout.log"
    echo "  stderr: $RUNTIME_DIR/frontend.stderr.log"
    echo "Frontend URL: http://$SAVED_HOST_ADDRESS:$SAVED_FRONTEND_PORT"
    echo "Backend URL:  http://$SAVED_HOST_ADDRESS:$SAVED_BACKEND_PORT"
}

stop_services() {
    load_state
    if [[ ! -f "$STATE_FILE" ]]; then
        echo "No saved service state."
        return 0
    fi

    if is_running "$FRONTEND_PID"; then
        stop_process_tree "$FRONTEND_PID"
        wait_for_exit "$FRONTEND_PID"
        echo "Stopped frontend pid=$FRONTEND_PID"
    else
        echo "Frontend was already stopped."
    fi

    if is_running "$BACKEND_PID"; then
        stop_process_tree "$BACKEND_PID"
        wait_for_exit "$BACKEND_PID"
        echo "Stopped backend pid=$BACKEND_PID"
    else
        echo "Backend was already stopped."
    fi

    rm -f "$STATE_FILE"
}

start_services() {
    local backend_stdout="$RUNTIME_DIR/backend.stdout.log"
    local backend_stderr="$RUNTIME_DIR/backend.stderr.log"
    local frontend_stdout="$RUNTIME_DIR/frontend.stdout.log"
    local frontend_stderr="$RUNTIME_DIR/frontend.stderr.log"
    local busy_pid

    [[ -f "$FRONTEND_DIR/package.json" ]] || { echo "Frontend package.json was not found." >&2; exit 1; }
    [[ -d "$FRONTEND_DIR/node_modules" ]] || {
        echo "Frontend dependencies are missing. Run: cd frontend && npm install" >&2
        exit 1
    }
    command -v lsof >/dev/null 2>&1 || { echo "lsof is required." >&2; exit 1; }
    command -v npm >/dev/null 2>&1 || { echo "npm is required." >&2; exit 1; }

    load_state
    if [[ -f "$STATE_FILE" ]] && { is_running "$BACKEND_PID" || is_running "$FRONTEND_PID"; }; then
        echo "Services already appear to be running. Use status, stop, or restart."
        show_status
        exit 1
    fi
    rm -f "$STATE_FILE"

    for port in "$BACKEND_PORT" "$FRONTEND_PORT"; do
        busy_pid="$(port_pid "$port")"
        if [[ -n "$busy_pid" ]]; then
            echo "Port $port is already in use by pid $busy_pid." >&2
            echo "Stop that service first. If Docker owns the port, run: docker compose down" >&2
            exit 1
        fi
    done

    mkdir -p "$RUNTIME_DIR"
    rm -f "$backend_stdout" "$backend_stderr" "$frontend_stdout" "$frontend_stderr"

    if [[ -x "$BACKEND_DIR/.venv/bin/python" ]]; then
        (
            cd "$BACKEND_DIR"
            exec "$BACKEND_DIR/.venv/bin/python" -m uvicorn app:app \
                --host "$HOST_ADDRESS" --port "$BACKEND_PORT" --reload
        ) >"$backend_stdout" 2>"$backend_stderr" &
    elif command -v conda >/dev/null 2>&1; then
        (
            cd "$BACKEND_DIR"
            exec conda run --no-capture-output -n codeagent python -m uvicorn app:app \
                --host "$HOST_ADDRESS" --port "$BACKEND_PORT" --reload
        ) >"$backend_stdout" 2>"$backend_stderr" &
    else
        echo "Backend Python was not found. Create backend/.venv or install Conda environment 'codeagent'." >&2
        exit 1
    fi
    BACKEND_PID=$!

    if ! wait_for_port "backend" "$BACKEND_PID" "$BACKEND_PORT" "$backend_stdout" "$backend_stderr"; then
        stop_process_tree "$BACKEND_PID"
        wait_for_exit "$BACKEND_PID"
        exit 1
    fi

    (
        cd "$FRONTEND_DIR"
        exec npm run dev -- --hostname "$HOST_ADDRESS"
    ) >"$frontend_stdout" 2>"$frontend_stderr" &
    FRONTEND_PID=$!

    if ! wait_for_port "frontend" "$FRONTEND_PID" "$FRONTEND_PORT" "$frontend_stdout" "$frontend_stderr"; then
        stop_process_tree "$FRONTEND_PID"
        stop_process_tree "$BACKEND_PID"
        wait_for_exit "$FRONTEND_PID"
        wait_for_exit "$BACKEND_PID"
        exit 1
    fi

    cat >"$STATE_FILE" <<EOF
BACKEND_PID=$BACKEND_PID
FRONTEND_PID=$FRONTEND_PID
SAVED_HOST_ADDRESS=$HOST_ADDRESS
SAVED_BACKEND_PORT=$BACKEND_PORT
SAVED_FRONTEND_PORT=$FRONTEND_PORT
EOF

    echo "Started services:"
    show_status
}

case "$ACTION" in
    start)
        start_services
        ;;
    stop)
        stop_services
        ;;
    restart)
        stop_services
        start_services
        ;;
    status)
        show_status
        ;;
esac
